### PR TITLE
Not pipe editor contents to stdin if the editor buffer is not modified

### PR DESCRIPTION
**Pull request by vzamanillo**
Implements #306 

We should not pipe contents to Rubocop `stdin` (Rubocop does not uses the cache) if the editor buffer is not modified so Rubocop would use the cache (enabled by default)

### CODE REVIEW

**Comment by vzamanillo** [comment]
We need to set `linter.lintOnChange` on tests, but I am thinking in execute each expectation with and without.

**Comment by Arcanemagus** [comment]
In other providers where we have wanted to change behavior like this [`TextEditor::isModified()`](https://atom.io/docs/api/v1.36.0/TextEditor#instance-isModified) is used to automatically change the behavior based on whether the buffer is modified.

With that while typing it would use the `stdin` approach, and when the file gets saved we would get a cached run on the file's contents directly.

**Comment by vzamanillo** [comment]
> In other providers where we have wanted to change behavior like this [`TextEditor::isModified()`](https://atom.io/docs/api/v1.36.0/TextEditor#instance-isModified) is used to automatically change the behavior based on whether the buffer is modified.
> 
> With that while typing it would use the `stdin` approach, and when the file gets saved we would get a cached run on the file's contents directly.

Sounds great, and easier than this pull request solution

```
if (editor.isModified()) {
  execOptions.stdin = editor.getText()
  command.push('--stdin', filePath)
} else {
  execOptions.ignoreExitCode = true
  command.push(filePath)
}
```

**Comment by vzamanillo** [comment]
This PR needs to be rewritten to to follow the required convention, so I will open a new PR soon.

**Comment by vzamanillo** [comment]
Tests are failing due to recent Rubocop 0.68.0 changes as commented [here](https://github.com/AtomLinter/linter-rubocop/pull/321/commits/67f4993e2769af0c741ff22a8cea53ad32025580), we should wait to merge that PR changes on master and rebase this branch to make the tests work.

**Pull request merged**
