### PR TITLE
Add docs for the 'command' config option

### PR DESCRIPTION
**Pull request by davefp**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
The description in the settings view has more information than this... if this is going to be in the readme it should show what the capabilities of the command are, justifying the reasoning for it's existence.

* Why does a user need it?
* How does a user use it?
* What will it do if changed?

**Comment by davefp** [comment]
Oh hey, I didn't realize this was in the atom settings page.

The current README only talks about `executablePath`, while the atom settings page only mentions `command`.  What's the difference between the two?

**Comment by Arcanemagus** [comment]
Essentially, none.

Back in https://github.com/AtomLinter/linter-rubocop/commit/5134f9e6deb4a3bcbeaaae704fe3cb97339f32b8 the `executablePath` and `additionalArguments` options were merged together into a single option, it looks like the readme was just never updated to account for it.

**Comment by davefp** [comment]
I'm going to close this then. Thanks for the help :)

**Pull request closed without merging**
