### PR TITLE
Fix #44, #51, others? Use provider API

### LINKED ISSUE #44: Linter rubocop not linterting.
As the title says it, simply nothing happens as I type code. I tried most troubleshooting tips that you can find out there. Modifying cson file, uninstalling everything (including atom), opening from terminal, etc. Any help appreciated. thank you.

### PR DESCRIPTION
**Pull request by caseywebdev**
Use JSON formatter, add additionalArguments param. [I made these same changes for linter-scss-lint](https://github.com/AtomLinter/linter-scss-lint/pull/42) and now that project is in a working state again.

### CODE REVIEW

**Comment by tfausak** [comment]
:+1:

**Comment by steelbrain** [comment]
The API you are using is depreciated, and we even discussed about removing it less than a week ago, but then thought to support it a few more weeks because a lot of linters are still using the legacy one.
I am not sure I can accept a PR that still uses the old one.
I suggest you upgrade it.

**Comment by caseywebdev** [comment]
@steelbrain I've updated the linter to use the new API. Unfortunately the rubocop binary cannot lint via stdin, so I had to create a tmpfile for lintOnFly to work. It'd be nice if the Linter plugin could do this automatically.

**Comment by steelbrain** [comment]
Alternatively You could disable `lintOnFly` and it's perfectly fine to do that.

**Comment by caseywebdev** [comment]
That makes the plugin a lot less useful, so that's not really an option IMO.

**Comment by steelbrain** [comment]
But writing to a file isn't really a good thing to do IMO. You could open up an issue at their repo asking for it to accept that.

**Comment by steelbrain** [comment]
But writing to a file isn't really a good thing to do IMO. You could open up an issue at their repo asking for it to accept that.

**Comment by caseywebdev** [comment]
[That has already been proposed for rubocop and the author unfortunately shot it down.](https://github.com/bbatsov/rubocop/issues/1682)

It's not fair of a linter plugin to ask a bunch of linter libraries to change to support it. I'm just saying it would be a nice convenience if Linter had an option to generate the temp file for `lintOnFly` linting.

**Comment by steelbrain** [comment]
For some reasons I am finding it quite funny 'cause he closed it because it would take a lot of effort, but still My opinion is against enabling `lintOnFly` when the linter doesn't support writes via stdin, but then again it's just my opinion. I would love to have other's.
/cc @AtomLinter/linter

**Comment by michaelglass** [comment]
disabling `lintOnTheFly` would completely ruin this plugin for me, fwiw

**Comment by steelbrain** [comment]
@michaelglass We have actually decided to support writing to temp files, but only for the providers that don't support it, I haven't gathered enough time to do it yet, but it's on the roadmap.

**Comment by michaelglass** [comment]
also: atom linter is awesome, thanks for all the work!

**Comment by caseywebdev** [comment]
@steelbrain @tfausak I've opened a PR on rubocop to support stdin, support would be appreciated as it will only improve the functionality of this plugin: https://github.com/bbatsov/rubocop/pull/2146

**Pull request merged**
