### PR TITLE
Fix spec failures due to Rubocop upgrade

### PR DESCRIPTION
**Pull request by maschwenk**
Fixes some of the Greenkeeper failures caused by Rubocop being upgraded. I think this probably warrants a separate piece piece of work where we just have a Gemfile/Gemfile.lock that will lock the Rubocop version but I will follow up with that, have some other PR's I'd like to build on this first.

### CODE REVIEW

**Comment by maschwenk** [comment]
What's up with appveyor? Doesn't give me option to restart

**Comment by Arcanemagus** [comment]
Restarted AppVeyor.

Unfortunately AppVeyor is behind _every_ other CI in that it has no concept of an organization account, thus most of these providers are registered under my account.... and there is no way for others to work on them.

**Comment by Arcanemagus** [comment]
Looks like AppVeyor is running on Ruby 2.3.3, is that what is causing the differing errors?

**Comment by Arcanemagus** [comment]
Wait... `Carriage return character missing. (Style/EndOfLine)` is it seriously trying to enforce `CRLF` on Windows?!?

**Comment by Arcanemagus** [comment]
`Expected 'Linter-Rubocop: Fixed 1 offense' to match /Linter-Rubocop: Fixed \d offenses/`

Looks like they are no longer pluralizing a single offense.

**Comment by maschwenk** [comment]
I think I could avoid changing the specs at all if I could just force AppVeyor to clone the repo in LF mode. Is that possible?

**Comment by maschwenk** [comment]
Actually, that won't work I think because of https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/cop/style/end_of_line.rb

**Comment by Arcanemagus** [comment]
The files are already being cloned with `LF` due to the [`.gitattributes`](https://github.com/AtomLinter/linter-rubocop/blob/master/.gitattributes) btw.

**Comment by maschwenk** [comment]
Right but if you look at the Rubocop source: 
```Ruby
effective_style = if style == :native
                              Platform.windows? ? :crlf : :lf
                            else
                              style
                            end
```

**Comment by maschwenk** [comment]
I spend like 90% of my time writing the specs trying to fix Windows issues, almost feels like it'd be faster to just fix the failures (if any) when they're reported....:(

**Comment by Arcanemagus** [comment]
> I think the solution here is to readd .rubocop.yml to the repo ... and then dynamically truncate/add to it for some of the tests involving the yml

You could just move the files needing individualized settings to folders and have a config file for each folder, that's the approach taken in a few other providers.

Btw, I'm almost always on [Atom's Slack](http://atom-slack.herokuapp.com/) if you would prefer to chat there on stuff like this. Much faster than the ~ day delay 😛.

**Pull request merged**
